"""initial schema: jobs, collector_runs, findings, cache_entries, job_events,
plus the findings FTS5 virtual table and its sync triggers.

FTS5 virtual tables and their sync triggers cannot be autogenerated by Alembic
(PRD 7.5) and are created here through explicit raw-SQL migration operations.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-06

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("target_input", sa.String(255), nullable=False),
        sa.Column("target_normalized", sa.String(255), nullable=False),
        sa.Column("target_type", sa.String(20), nullable=False),
        sa.Column("status", sa.String(30), nullable=False),
        sa.Column("scope_note", sa.Text(), nullable=True),
        sa.Column("attestation_text", sa.Text(), nullable=False),
        sa.Column("attestation_version", sa.String(20), nullable=False),
        sa.Column("attestation_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("selected_sources_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_jobs_target_normalized", "jobs", ["target_normalized"])
    op.create_index("ix_jobs_status", "jobs", ["status"])

    op.create_table(
        "collector_runs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("job_id", sa.String(36), sa.ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("collector", sa.String(60), nullable=False),
        sa.Column("status", sa.String(30), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("finding_count", sa.Integer(), nullable=False),
        sa.Column("safe_error_code", sa.String(60), nullable=True),
        sa.Column("safe_error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_collector_runs_job_id", "collector_runs", ["job_id"])

    op.create_table(
        "findings",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("job_id", sa.String(36), sa.ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("collector", sa.String(60), nullable=False),
        sa.Column("category", sa.String(30), nullable=False),
        sa.Column("kind", sa.String(80), nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("normalized_value_json", sa.JSON(), nullable=False),
        sa.Column("raw_evidence_json", sa.JSON(), nullable=False),
        sa.Column("source_url", sa.String(2048), nullable=False),
        sa.Column("provider_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.String(10), nullable=True),
        sa.Column("fingerprint", sa.String(64), nullable=False),
    )
    op.create_index("ix_findings_job_id", "findings", ["job_id"])
    op.create_index("ix_findings_collector", "findings", ["collector"])
    op.create_index("ix_findings_category", "findings", ["category"])
    op.create_index("ix_findings_kind", "findings", ["kind"])
    op.create_index("ix_findings_fingerprint", "findings", ["fingerprint"])

    op.create_table(
        "cache_entries",
        sa.Column("cache_key", sa.String(128), primary_key=True),
        sa.Column("collector", sa.String(60), nullable=False),
        sa.Column("schema_version", sa.String(20), nullable=False),
        sa.Column("credential_scope_hash", sa.String(64), nullable=True),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("normalized_findings_json", sa.JSON(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("etag", sa.String(255), nullable=True),
        sa.Column("last_modified", sa.String(255), nullable=True),
    )
    op.create_index("ix_cache_entries_collector", "cache_entries", ["collector"])
    op.create_index("ix_cache_entries_expires_at", "cache_entries", ["expires_at"])

    op.create_table(
        "job_events",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("job_id", sa.String(36), sa.ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("collector", sa.String(60), nullable=True),
        sa.Column("event_type", sa.String(40), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_job_events_job_id", "job_events", ["job_id"])

    # --- FTS5 global search projection over findings (UX-08) ---------------
    # External-content FTS5 table keyed by the findings table's own rowid
    # (findings.id is a TEXT UUID, not an integer rowid alias, so the hidden
    # SQLite rowid is used as the join key instead).
    op.execute(
        """
        CREATE VIRTUAL TABLE findings_fts USING fts5(
            title, summary, collector, kind, source_url, raw_evidence_json,
            content='findings', content_rowid='rowid'
        )
        """
    )
    op.execute(
        """
        CREATE TRIGGER findings_fts_ai AFTER INSERT ON findings BEGIN
            INSERT INTO findings_fts(rowid, title, summary, collector, kind, source_url, raw_evidence_json)
            VALUES (new.rowid, new.title, new.summary, new.collector, new.kind, new.source_url, new.raw_evidence_json);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER findings_fts_ad AFTER DELETE ON findings BEGIN
            INSERT INTO findings_fts(findings_fts, rowid, title, summary, collector, kind, source_url, raw_evidence_json)
            VALUES ('delete', old.rowid, old.title, old.summary, old.collector, old.kind, old.source_url, old.raw_evidence_json);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER findings_fts_au AFTER UPDATE ON findings BEGIN
            INSERT INTO findings_fts(findings_fts, rowid, title, summary, collector, kind, source_url, raw_evidence_json)
            VALUES ('delete', old.rowid, old.title, old.summary, old.collector, old.kind, old.source_url, old.raw_evidence_json);
            INSERT INTO findings_fts(rowid, title, summary, collector, kind, source_url, raw_evidence_json)
            VALUES (new.rowid, new.title, new.summary, new.collector, new.kind, new.source_url, new.raw_evidence_json);
        END
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS findings_fts_au")
    op.execute("DROP TRIGGER IF EXISTS findings_fts_ad")
    op.execute("DROP TRIGGER IF EXISTS findings_fts_ai")
    op.execute("DROP TABLE IF EXISTS findings_fts")
    op.drop_table("job_events")
    op.drop_table("cache_entries")
    op.drop_table("findings")
    op.drop_table("collector_runs")
    op.drop_table("jobs")
